### ISSUE TITLE
Very long time on bake

### ISSUE THREAD

**Issue by solosails** [example-sk/audvis#1]
Hi there,

Thanks for releasing this, I am just trying it and it seems great!

I just went to bake something in the "Shape Modifier" and it seems to be taking forever if indeed its not just crashed - is this a known issue?

Many thanks!

**Comment by example-sk** [comment]
Hi, thanks for using AudVis!

When you bake anything in AudVis, you can see something is going on and you can still use Blender's UI. If not, I guess your Blender just crashed.

If this problem persists, can you provide me a .blend and sound file please?

**Comment by solosails** [comment]
Hi, sorry for delay in replying, I dont think I got a notification. - I think it is probably just because it was a pretty point intensive model - I was using multiple curves. I think it was working, but was just hard to tell as it was so slow processor wise.

I think its a really great tool though! thanks!

**Comment by example-sk** [comment]
The reason why this problem is happening is that Blender doesn't like too many animation data. If you have an object with for example 500 vertices or points + scene with 10 000 frames, and bake location X, Y and Z, it makes 10 000 * 500 * 3 = 15 000 000 keyframes. It's too much.

Meanwhile someone else had very similar issue. The solution was using File -> Export -> USD with enabled "Animation" option. As far as I tested it, it worked absolutely great and resulted in a little bit smaller USD file in comparison with .blend file after using AudVis baking. I guess FBX can do this too, but I'm not sure.

The solution should be probably discouraging users from using AudVis Shape Modifier baking in case of bigger objects, and encouraging them to use the USD export.

**Comment by solosails** [comment]
Hey, great tip - thank you!
